In [ ]:
import numpy as np

In [ ]:
a = [2, 5, 7]

In [ ]:
b = [3, 12, 27]

In [ ]:
a+b

In [ ]:
c = [m+n for m, n in zip(a,b)]

In [ ]:
c

In [ ]:
sum(a)

In [ ]:
np_a = np.array(a)

In [ ]:
np_b = np.array(b)

In [ ]:
np_a + np_b

In [ ]:
p = np.array([1,2,"abc"])

In [ ]:
p

In [ ]:
p+ np_a

In [ ]:
np_a.max()

In [ ]:
np_a.mean()

In [ ]:
np.ones(3)

In [ ]:
np.zeros(3)

In [ ]:
np_a*np.ones(3)

In [ ]:
np_a*[3]

In [ ]:
np_a*np.array([2.2])

In [ ]:
np_a*np.array([2.2,3.2])

In [ ]:
np_a[1]

In [ ]:
np_a[1:]

In [ ]:
np_a[0:2]

In [ ]:
np_2d = np.array([[1,2],[3,4]])

In [ ]:
np_2d.sum()

In [ ]:
np_2d.sum(axis=0)

In [ ]:
np_2d.sum(axis=1)

In [ ]:
np_2d.T()

In [ ]:
np_2d.T

In [ ]:
np.ones([2,2])

In [ ]:
np.eye(2)

In [ ]:
np_2d

In [ ]:
np_2d+np.ones([2,2])

In [ ]:
np_2d+np.ones(2)

In [ ]:
np_2d+np.ones([2,1])

In [ ]:
np_dotp = np_2d.dot(np.array([[1,10,100],[1000,100,10]]))

In [ ]:
np_dotp

In [ ]:
np_dotp[0,1]

In [ ]:
np_dotp[1:3]

In [ ]:
np_dotp[0:2,0]

In [ ]:
np_rs = np.array([1,2,3,4,5,6])

In [ ]:
np_rs

In [ ]:
np_rs.reshape(2,3)

In [ ]:
np_rs.reshape(3,2)

In [ ]:
np_rs.reshape(3,-1)

In [ ]:
np_rs.reshape(4,-1)

In [ ]:
np_rs.reshape(2,-1)

In [ ]:
np_rs.reshape(2,2,-1)

In [ ]:
np_rs.reshape(-1,3)

In [ ]:
np.random(2)

In [ ]:
np.random.random(2)

In [ ]:
import np.random as random

In [ ]:
import numpy.random as random

In [ ]:
random(2)

In [ ]:
random.random(2)

In [ ]:
random.random([3,2])

In [ ]:
import numpy.linalg as la

In [ ]:
la.inv(np_2d)

In [ ]:
la.eig(np_2d)

In [ ]:
la.svd(np_2d)

In [ ]:
la.pinv(np_2d)

In [ ]:
random.rand(2,3)*5

In [ ]:
random.randn(2,3)

In [ ]:
random.randint(-2,3,5)

In [ ]:
random.shuffle(np_rs)

In [ ]:
np_rs

In [ ]:
random.choice(np_rs, 2)

In [ ]:
random.binomial(20,0.3)

In [ ]:
random.binomial(20, 0.3, 7)

In [ ]:
random.exponential(0.7,4)

In [ ]:
%%time


In [ ]:
random.normal(-5,12,3)

In [ ]:
random.logistic(-2,4,7)

In [ ]:
np_2d.shape

In [ ]:
np_2d.dtype

In [ ]:
type(np_2d)

In [ ]:
np.vstack(np.ones([2,2]))

In [ ]:
np.vstack((np_2d,np.ones([2,2])))

In [ ]:
np.hstack((np_2d,np.ones([2,2])))

In [ ]:
N=10000000
x=list(range(N))
y=list(range(N)) 
z=[]

In [ ]:
np_x = np.array(x)
np_y = np.array(y)

In [ ]:
%%time
for i in range(len(x)):
    z.append(x[i]+y[i])


In [ ]:
%%time
np_z = np_x+np_y

In [ ]:
Newton Method
Perform this matrix computation -> ((X'X)^-1)*X'y, use only X and y values from rows 2 to 41
Error Computation (both Training and Test Error)
Generate y values from the new generated w values
Compute the SSR, MSR and RMSE between the generated y values and the actual values both for the data from rows 2 to 41 and the data from rows 43 to 51
Regularized Newton
Next step perform the matrix computation -> ((X'X+lambda*I)^-1)*X'y, using only X and y values from rows 2 to 41
Use lambda as 0.17
Compute and report both training and test errors for the regularized newton computation
Compute R-squared values for both Newton and Regularized Newton on both train and test datasets
Look up how to compute R-squared values in excel
Let's try some more things
For each of the below report the following, MSR on train, MSR on test, R-squared on train and R-squared on test
1. Use only rows 2 to 41 for training and rows 42 to 51 for testing and lambda as 0.83
2. Use only rows 2 to 26 for training and rows 27 to 51 for testing and lambda as 0.17
3. Use only rows 2 to 26 for training and rows 27 to 51 for testing and lambda as 0.83
4. Use only rows 2 to 11 for training and rows 12 to 51 for testing and lambda as 0.17
5. Use only rows 2 to 11 for training and rows 12 to 51 for testing and lambda as 0.83


In [1]:
import pandas as pd
import numpy as np

csv_file = pd.read_csv("C:\\PG AI and DS\\Python\\Assignments\\AISC1000_Python\\NumpyExerciseData.csv")
csv_file

X0     X1     X2  X3  X4   X5   y  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0    1  5.768  62.55   0  28  2.6  28         NaN         NaN         NaN   
1    1  8.949  66.91   0  27 -2.0  46         NaN         NaN         NaN   
2    1  1.024  34.42   0  20 -3.4  14         NaN         NaN         NaN   
3    1  4.534  47.93   0  10  1.1  17         NaN         NaN         NaN   
4    1  8.641  35.26   0  30  3.8  32         NaN         NaN         NaN   
5    1  1.063  42.14   0   6 -2.1   8         NaN         NaN         NaN   
6    1  5.306  39.80   0  29 -1.8  30         NaN         NaN         NaN   
7    1  4.309  36.14   0  12 -3.4  22         NaN         NaN         NaN   
8    1  3.739  44.53   0  39  1.9  24         NaN         NaN         NaN   
9    1  3.816  60.01   0  10 -3.4  24         NaN         NaN         NaN   
10   1  8.539  36.90   0  31 -3.0  43         NaN         NaN         NaN   
11   1  7.129  35.77   0  38  3.5  30         NaN         NaN         NaN   
12   1  4.249  37.17   0  23  0.8  20         NaN         NaN         NaN   
13   1 -2.990  42.41   0  20 -3.1   2         NaN         NaN         NaN   
14   1  0.356  57.67   0  26 -3.8  19         NaN         NaN         NaN   
15   1  5.487  35.25   0  10 -2.8  24         NaN         NaN         NaN   
16   1  5.699  62.15   0  13  2.4  22         NaN         NaN         NaN   
17   1 -0.373  38.38   1  42  2.0  23         NaN         NaN         NaN   
18   1  3.900  40.53   0  23 -2.5  25         NaN         NaN         NaN   
19   1  3.616  35.91   1  16  3.1  23         NaN         NaN         NaN   
20   1  9.103  59.60   0  14  2.2  34         NaN         NaN         NaN   
21   1  2.714  43.54   0  37  2.1  19         NaN         NaN         NaN   
22   1  6.885  35.66   1  20 -3.7  46         NaN         NaN         NaN   
23   1 -0.850  43.94   1  31 -3.2  26         NaN         NaN         NaN   
24   1  5.511  58.96   0   6 -3.8  28         NaN         NaN         NaN   
25   1  5.225  45.25   0  24 -1.3  28         NaN         NaN         NaN   
26   1  7.982  43.71   0  27  2.0  33         NaN         NaN         NaN   
27   1  4.361  52.71   0  22 -2.5  28         NaN         NaN         NaN   
28   1  2.853  51.12   0  42  2.3  22         NaN         NaN         NaN   
29   1  2.777  38.60   1  24 -2.5  33         NaN         NaN         NaN   
30   1  1.977  49.07   0  41 -3.6  28         NaN         NaN         NaN   
31   1  3.784  45.44   0  12 -1.9  20         NaN         NaN         NaN   
32   1  3.043  62.50   0  25 -1.9  25         NaN         NaN         NaN   
33   1  5.618  52.44   0  27  1.1  28         NaN         NaN         NaN   
34   1  7.374  38.25   0  36  3.1  31         NaN         NaN         NaN   
35   1  3.090  56.77   0  49 -1.7  33         NaN         NaN         NaN   
36   1  6.178  61.51   1   6 -2.5  41         NaN         NaN         NaN   
37   1  4.605  58.22   0  41  0.2  32         NaN         NaN         NaN   
38   1  1.968  65.84   0  76  3.5  33         NaN         NaN         NaN   
39   1  3.610  45.18   1  43  2.5  36         NaN         NaN         NaN   
40   1  9.896  65.18   0  69  2.3  58         NaN         NaN         NaN   
41   1 -0.256  53.70   0  13  0.3   5         NaN         NaN         NaN   
42   1  4.545  39.25   1  18  2.2  29         NaN         NaN         NaN   
43   1  3.121  36.89   0  20  4.1  10         NaN         NaN         NaN   
44   1  4.698  40.65   0   8 -1.8  20         NaN         NaN         NaN   
45   1 -0.328  49.64   0  18  0.5   6         NaN         NaN         NaN   
46   1  5.216  44.49   1  11  3.2  28         NaN         NaN         NaN   
47   1 -2.111  51.31   0  25  2.6  -1         NaN         NaN         NaN   
48   1  6.804  36.12   0  24  3.0  25         NaN         NaN         NaN   
49   1  5.643  39.06   0  35 -1.9  34         NaN         NaN         NaN   

    Unnamed: 10  
0           NaN  
1           NaN  
2           NaN  
3   

In [2]:
csv_file = csv_file.drop(columns=["Unnamed: 7", "Unnamed: 8", "Unnamed: 9", "Unnamed: 10"])
csv_file.head()

X0     X1     X2  X3  X4   X5   y
0   1  5.768  62.55   0  28  2.6  28
1   1  8.949  66.91   0  27 -2.0  46
2   1  1.024  34.42   0  20 -3.4  14
3   1  4.534  47.93   0  10  1.1  17
4   1  8.641  35.26   0  30  3.8  32

Newtons

In [4]:
X_train = csv_file.iloc[1:41, :6].values
y_train = csv_file.iloc[1:41, -1].values

In [5]:
X_train.shape, y_train.shape

((40, 6), (40,))

In [7]:
X_train = np.hstack((np.ones((X_train.shape[0], 1)), X_train))
X_train

array([[ 1.   ,  1.   ,  1.   ,  8.949, 66.91 ,  0.   , 27.   , -2.   ],
       [ 1.   ,  1.   ,  1.   ,  1.024, 34.42 ,  0.   , 20.   , -3.4  ],
       [ 1.   ,  1.   ,  1.   ,  4.534, 47.93 ,  0.   , 10.   ,  1.1  ],
       [ 1.   ,  1.   ,  1.   ,  8.641, 35.26 ,  0.   , 30.   ,  3.8  ],
       [ 1.   ,  1.   ,  1.   ,  1.063, 42.14 ,  0.   ,  6.   , -2.1  ],
       [ 1.   ,  1.   ,  1.   ,  5.306, 39.8  ,  0.   , 29.   , -1.8  ],
       [ 1.   ,  1.   ,  1.   ,  4.309, 36.14 ,  0.   , 12.   , -3.4  ],
       [ 1.   ,  1.   ,  1.   ,  3.739, 44.53 ,  0.   , 39.   ,  1.9  ],
       [ 1.   ,  1.   ,  1.   ,  3.816, 60.01 ,  0.   , 10.   , -3.4  ],
       [ 1.   ,  1.   ,  1.   ,  8.539, 36.9  ,  0.   , 31.   , -3.   ],
       [ 1.   ,  1.   ,  1.   ,  7.129, 35.77 ,  0.   , 38.   ,  3.5  ],
       [ 1.   ,  1.   ,  1.   ,  4.249, 37.17 ,  0.   , 23.   ,  0.8  ],
       [ 1.   ,  1.   ,  1.   , -2.99 , 42.41 ,  0.   , 20.   , -3.1  ],
       [ 1.   ,  1.   ,  1.   ,  0.356, 57.67 ,  0.

In [8]:
# computing the pseudo-inverse of (X^T*X)
X_tran_pinv_X = np.linalg.pinv(np.dot(X_train.T, X_train))
X_tran_pinv_X

array([[ 7.96549761e-02,  7.96549761e-02,  7.96549761e-02,
        -5.13632638e-03, -3.67461113e-03, -4.02317563e-02,
        -8.75070458e-04,  4.72242916e-03],
       [ 7.96549761e-02,  7.96549761e-02,  7.96549761e-02,
        -5.13632638e-03, -3.67461113e-03, -4.02317563e-02,
        -8.75070458e-04,  4.72242916e-03],
       [ 7.96549761e-02,  7.96549761e-02,  7.96549761e-02,
        -5.13632638e-03, -3.67461113e-03, -4.02317563e-02,
        -8.75070458e-04,  4.72242916e-03],
       [-5.13632638e-03, -5.13632638e-03, -5.13632638e-03,
         3.74383963e-03, -1.43240965e-04,  4.85835606e-03,
         1.53264469e-04, -1.63683045e-03],
       [-3.67461113e-03, -3.67461113e-03, -3.67461113e-03,
        -1.43240965e-04,  2.69855722e-04,  1.30388694e-03,
        -4.84086991e-05,  1.75956809e-04],
       [-4.02317563e-02, -4.02317563e-02, -4.02317563e-02,
         4.85835606e-03,  1.30388694e-03,  1.88171717e-01,
         1.38157785e-04, -1.46562315e-03],
       [-8.75070458e-04, -8.750704

In [9]:
# computing the weights
weight = np.dot(np.dot(X_tran_pinv_X, X_train.T), y_train)
weight

array([-2.61065458, -2.61065458, -2.61065458,  3.26458338,  0.16631204,
       12.19246692,  0.38231333, -1.58835343])

In [10]:
# generating y values from the new generated w values
y_pred_train = np.dot(X_train, weight)
y_pred_train

array([46.00989848, 14.28209844, 17.016938  , 31.67512079,  8.27610001,
       30.05525777, 22.23380488, 23.67253722, 23.82960703, 42.7980017 ,
       30.35890257, 19.74359354,  2.03038794, 18.89733308, 24.21382766,
       22.2672154 , 22.40632288, 24.40462873, 23.33061978, 33.65574554,
       19.07939298, 46.29102151, 25.82780273, 28.29453625, 27.99148376,
       32.64119327, 27.55296899, 22.38771132, 32.9922996 , 28.17596851,
       19.68407044, 25.07237092, 27.80514037, 31.44189406, 33.13068768,
       41.02371652, 32.24130577, 33.03929752, 36.12821698, 58.04097939])

In [11]:
SSR_train = np.sum((y_train - y_pred_train) ** 2)
MSR_train = SSR_train / (len(y_train))
RMSE_train = np.sqrt(MSR_train)

In [12]:
# getting X_test and y_test values from rows 43 to 50 in matrices
X_test = csv_file.iloc[42:51, :6]
y_test = csv_file.iloc[42:51, -1]
X_test.shape,y_test.shape



((8, 6), (8,))

In [13]:
# adding a column of ones to X_train
X_test = np.hstack((np.ones((X_test.shape[0], 1)), X_test))
X_test

# computing the pseudo-inverse of (X^T*X)
X_tran_pinv_X1 = np.linalg.pinv(np.dot(X_test.T, X_test))
X_tran_pinv_X1

# computing the weights
weight1 = np.dot(np.dot(X_tran_pinv_X1, X_test.T), y_test)
weight1

# generating y values from the new generated w values
y_pred_test = np.dot(X_test, weight1)
y_pred_test



array([29.10484845,  9.78787445, 20.23022966,  5.54357092, 27.89515155,
       -0.59718708, 25.13007152, 33.90544053])

In [16]:
SSR_test = np.sum((y_test - y_pred_test) ** 2)
MSR_test = SSR_test / (len(y_test))
RMSE_test = np.sqrt(MSR_test)
SSR_test,MSR_test,RMSE_test

(0.5164351933231227, 0.06455439916539034, 0.25407557766418704)

Newton method computation with λ = 0.17

In [17]:
# declaring lambda as 0.17
lambda_reg = 0.17
# computing the pseudo-inverse of (X'X+lambda*I)^-1)
X_tran_reg_pinv_X = np.linalg.pinv(np.dot(X_train.T, X_train) + lambda_reg * np.eye(X_train.shape[1]))
X_tran_reg_pinv_X

array([[ 3.99785797e+00, -1.88449497e+00, -1.88449497e+00,
        -4.90122945e-03, -3.52343703e-03, -3.74620792e-02,
        -8.39676649e-04,  4.52382052e-03],
       [-1.88449497e+00,  3.99785797e+00, -1.88449497e+00,
        -4.90122945e-03, -3.52343703e-03, -3.74620792e-02,
        -8.39676649e-04,  4.52382052e-03],
       [-1.88449497e+00, -1.88449497e+00,  3.99785797e+00,
        -4.90122945e-03, -3.52343703e-03, -3.74620792e-02,
        -8.39676649e-04,  4.52382052e-03],
       [-4.90122945e-03, -4.90122945e-03, -4.90122945e-03,
         3.72436655e-03, -1.53299844e-04,  4.60696892e-03,
         1.50742323e-04, -1.62131564e-03],
       [-3.52343703e-03, -3.52343703e-03, -3.52343703e-03,
        -1.53299844e-04,  2.62966333e-04,  1.19352785e-03,
        -4.99876171e-05,  1.84513942e-04],
       [-3.74620792e-02, -3.74620792e-02, -3.74620792e-02,
         4.60696892e-03,  1.19352785e-03,  1.81589750e-01,
         1.16958911e-04, -1.32766202e-03],
       [-8.39676649e-04, -8.396766

In [18]:
# computing the weights
weight_reg = np.dot(np.dot(X_tran_reg_pinv_X, X_train.T), y_train)
weight_reg

array([-2.4273362 , -2.4273362 , -2.4273362 ,  3.24599857,  0.15927768,
       11.76324743,  0.38073989, -1.57717972])

In [19]:
y_pred_train_reg = np.dot(X_train, weight_reg)
y_pred_train_reg

array([45.85803875, 14.50144056, 17.14202947, 31.8117098 ,  8.4769662 ,
       30.16089178, 22.39258438, 23.79962938, 23.83278564, 42.84739529,
       30.50406458, 19.92586442,  2.2714771 , 18.95163087, 24.36682595,
       22.28043249, 22.22027464, 24.532877  , 23.14101233, 33.61982934,
       19.23788023, 45.96014383, 25.57071302, 28.27542399, 28.07373999,
       32.715197  , 27.58854465, 22.48466236, 32.72420199, 28.2392688 ,
       19.80394803, 25.06555889, 27.85161232, 31.563735  , 33.127781  ,
       40.55957692, 32.23386093, 33.00906159, 35.82432521, 57.86565141])

Testing Computation

In [20]:
# computing the pseudo-inverse of (X'X+lambda*I)^-1)
X_tran_reg_pinv_X1 = np.linalg.pinv(np.dot(X_test.T, X_test) + lambda_reg * np.eye(X_test.shape[1]))
X_tran_reg_pinv_X1

array([[ 5.38048147e+00, -5.01871476e-01, -1.73705950e-01,
        -9.66703711e-02,  2.81002483e-01, -8.68499136e-03,
        -6.00759184e-02],
       [-5.01871476e-01,  5.38048147e+00, -1.73705950e-01,
        -9.66703711e-02,  2.81002483e-01, -8.68499136e-03,
        -6.00759184e-02],
       [-1.73705950e-01, -1.73705950e-01,  2.77180790e-02,
         6.94469159e-03, -7.08120541e-02, -1.57184609e-03,
         7.77126904e-03],
       [-9.66703711e-02, -9.66703711e-02,  6.94469159e-03,
         4.39475501e-03, -1.91834128e-02, -5.92919083e-04,
         1.79633785e-03],
       [ 2.81002483e-01,  2.81002483e-01, -7.08120541e-02,
        -1.91834128e-02,  9.26927863e-01,  1.75743788e-02,
        -6.43490606e-02],
       [-8.68499136e-03, -8.68499136e-03, -1.57184609e-03,
        -5.92919083e-04,  1.75743788e-02,  2.23956517e-03,
        -6.20369010e-04],
       [-6.00759184e-02, -6.00759184e-02,  7.77126904e-03,
         1.79633785e-03, -6.43490606e-02, -6.20369010e-04,
         3.1787249

In [21]:
# computing the weights
weight_reg_test = np.dot(np.dot(X_tran_reg_pinv_X1, X_test.T), y_test)
weight_reg_test

array([-1.20859797, -1.20859797,  3.18255534,  0.07293882, 10.52600926,
        0.34775951, -1.5305359 ])

In [22]:
y_pred_test_reg = np.dot(X_test, weight_reg_test)
y_pred_test_reg

array([28.32886843, 10.88626556, 21.03645295,  5.65401242, 26.88171   ,
       -0.67848471, 25.62608152, 33.47055549])

In [23]:
SSR_train_reg = np.sum((y_train - y_pred_train_reg)**2)
MSR_train_reg = SSR_train_reg / (len(y_train))
RMSE_train_reg = np.sqrt(MSR_train_reg)
SSR_train_reg,MSR_train_reg,RMSE_train_reg

(4.004447664890845, 0.10011119162227114, 0.3164035265642138)

In [24]:
SSR_test_reg = np.sum((y_test - y_pred_test_reg) ** 2)
MSR_test_reg = SSR_test_reg / (len(y_test))
RMSE_test_reg = np.sqrt(MSR_test_reg)
SSR_test_reg,MSR_test_reg,RMSE_test_reg

(4.456060534201329, 0.5570075667751662, 0.7463293956257961)

In [26]:
#MSR on train, MSR on test, R-squared on train and R-squared on test for the following:
# defining r-squared function
def r_squared(y_actual, y_pred):
    ss_total = np.sum((y_actual - np.mean(y_actual)) ** 2)
    ss_res = np.sum((y_actual - y_pred) ** 2)
    return 1 - (ss_res / ss_total)
# creating a function for the computation of MSR and R-Squared
def computations(train_rows, test_rows, lambda_val):
    
    # extracting X and y values for training
    np_df=pd.read_csv("C:\\PG AI and DS\\Python\\Assignments\\AISC1000_Python\\NumpyExerciseData.csv")
    X_train = np_df.iloc[train_rows[0]:train_rows[1], :6].values
    y_train = np_df.iloc[train_rows[0]:train_rows[1], :6].values
    X_train = np.hstack((np.ones((X_train.shape[0], 1)), X_train))
    
    # extracting X and y values for test
    X_test = np_df.iloc[test_rows[0]:test_rows[1], :6].values
    y_test = np_df.iloc[test_rows[0]:test_rows[1], :6].values
    X_test = np.hstack((np.ones((X_test.shape[0], 1)), X_test))
    
    # regularizing Newton method
    # training computation
    X_reg_pinv_train = np.linalg.pinv(np.dot(X_train.T, X_train) + lambda_val * np.eye(X_train.shape[1])) 
    weight_reg_train = np.dot(np.dot(X_reg_pinv_train, X_train.T), y_train)
    
    # testing computation
    X_reg_pinv_test = np.linalg.pinv(np.dot(X_test.T, X_test) + lambda_val * np.eye(X_test.shape[1])) 
    weight_reg_test = np.dot(np.dot(X_reg_pinv_test, X_test.T), y_test)
    
    # generating y values from the weights
    y_pred_train_reg = np.dot(X_train, weight_reg_train)
    y_pred_test_reg = np.dot(X_test, weight_reg_test)
    
    # computing SSR and MSR for training
    SSR_train_reg = np.sum((y_train - y_pred_train_reg) ** 2)
    MSR_train_reg = SSR_train_reg / (len(y_train))
    
    # computing SSR and MSR for testing
    SSR_test_reg = np.sum((y_test - y_pred_test_reg) ** 2)
    MSR_test_reg = SSR_test_reg / (len(y_test))
    
    # computing R-squared values
    R2_train_reg = r_squared(y_train, y_pred_train_reg)
    R2_test_reg = r_squared(y_test, y_pred_test_reg)
    
    return MSR_train_reg, MSR_test_reg, R2_train_reg, R2_test_reg

In [27]:
results = []

scenarios = [
    ([1, 41], [41, 51], 0.83),
    ([1, 26], [26, 51], 0.17),
    ([1, 26], [26, 51], 0.83),
    ([1, 11], [11, 51], 0.17),
    ([1, 11], [11, 51], 0.83),
]

for scenario in scenarios:
    results.append(computations(*scenario))

# Print results
for i, result in enumerate(results):
    print(f"\nCase {i + 1}: \nMSR Train: {result[0]}, \nMSR Test: {result[1]}, \nR-squared Train: {result[2]}, \nR-squared Test: {result[3]}")


Case 1: 
MSR Train: 0.00428586969491983, 
MSR Test: 0.02777351095522945, 
R-squared Train: 0.9999981579049236, 
R-squared Test: 0.9999826741680861

Case 2: 
MSR Train: 0.0007181400881850452, 
MSR Test: 0.0007063155994490736, 
R-squared Train: 0.9999996183026731, 
R-squared Test: 0.9999997188042986

Case 3: 
MSR Train: 0.009844520890579647, 
MSR Test: 0.009789692077646612, 
R-squared Train: 0.9999947675566785, 
R-squared Test: 0.9999961025647283

Case 4: 
MSR Train: 0.0014206402809189944, 
MSR Test: 0.00025047051091760253, 
R-squared Train: 0.9999992385432711, 
R-squared Test: 0.9999998901148855

Case 5: 
MSR Train: 0.013155322708161258, 
MSR Test: 0.0041967011103176514, 
R-squared Train: 0.9999929488068645, 
R-squared Test: 0.9999981588452056
